# Generated by Django 5.2.14 on 2026-06-02 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilitySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('is_booked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['start_at'],
                'indexes': [models.Index(fields=['start_at', 'is_booked'], name='bookings_av_start_a_c520c2_idx')],
            },
        ),
        migrations.CreateModel(
            name='CallBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=120)),
                ('guest_email', models.EmailField(max_length=254)),
                ('topic', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending_payment', 'Paiement en attente'), ('confirmed', 'Confirmé'), ('completed', 'Terminé'), ('cancelled', 'Annulé')], default='pending_payment', max_length=30)),
                ('amount_cents', models.PositiveIntegerField(default=0)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=120)),
                ('meeting_link', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='bookings.availabilityslot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
