# Generated by Django 5.2.14 on 2026-06-02 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=120)),
                ('sender_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField()),
                ('tier', models.CharField(choices=[('free', 'Gratuit'), ('premium', 'Premium')], default='free', max_length=20)),
                ('status', models.CharField(choices=[('pending_payment', 'Paiement en attente'), ('paid', 'Payé'), ('analyzing', 'Analyse en cours'), ('analyzed', 'Analysé'), ('archived', 'Archivé')], default='analyzing', max_length=30)),
                ('is_priority', models.BooleanField(default=False)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=120)),
                ('amount_cents', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_priority', '-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='messages_ap_created_89732c_idx'), models.Index(fields=['tier', 'status'], name='messages_ap_tier_833ee0_idx')],
            },
        ),
        migrations.CreateModel(
            name='MessageAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True)),
                ('relevance_score', models.FloatField(default=0.0)),
                ('opportunity_detected', models.BooleanField(default=False)),
                ('opportunity_details', models.TextField(blank=True)),
                ('suggested_reply', models.TextField(blank=True)),
                ('sentiment', models.CharField(blank=True, max_length=40)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('raw_ai_response', models.JSONField(blank=True, default=dict)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='messages_app.inboundmessage')),
            ],
        ),
    ]
